import { ArrowRight, BellRing, HeartHandshake, Layers3, Monitor, ShieldCheck, Smartphone, Stethoscope, TimerReset } from 'lucide-react'
import { navigate } from '../lib/navigation'
import { CurrentSituationOverview } from '../components/CurrentSituationOverview'
import { BrandMark } from '../components/BrandMark'
import { useDemoData } from '../context/DemoDataContext'

const experiences = [
  { icon: Smartphone, number: '01', title: 'Esperienza paziente', text: 'Un percorso mobile anonimo, accessibile con il solo codice ticket.', path: '/mobile', action: 'Prova il mobile', tone: 'from-cyan-50 to-white text-cyan-800' },
  { icon: Monitor, number: '02', title: 'Display sala d’attesa', text: 'Situazione leggibile da lontano, chiamate chiare e privacy rispettata.', path: '/display', action: 'Apri il display', tone: 'from-blue-50 to-white text-blue-800' },
  { icon: Stethoscope, number: '03', title: 'Area operatore', text: 'Una console credibile per gestire priorità, stati e comunicazioni.', path: '/login', action: 'Accedi alla dashboard', tone: 'from-violet-50 to-white text-violet-800' },
]

export function LandingPage() {
  const { patients } = useDemoData()
  return <><section className="relative overflow-hidden bg-[linear-gradient(145deg,#f8fbfc_0%,#eef8f7_52%,#eef3ff_100%)]"><div className="absolute -right-24 -top-24 h-[480px] w-[480px] rounded-full bg-cyan-200/30 blur-3xl" /><div className="absolute -bottom-32 left-1/3 h-80 w-80 rounded-full bg-violet-200/25 blur-3xl" /><div className="container-page relative grid min-h-[690px] items-center gap-14 py-16 lg:grid-cols-[1.08fr_.92fr] lg:py-24"><div><BrandMark /><div className="mt-8 inline-flex items-center gap-2 rounded-full border border-teal-200/80 bg-white/70 px-3 py-1.5 text-xs font-black uppercase tracking-[.14em] text-teal-800 shadow-sm backdrop-blur"><Layers3 size={14} /> UX · Service design · Healthcare</div><h1 className="mt-6 max-w-3xl text-5xl font-black leading-[1.02] tracking-[-.05em] text-[#102f46] sm:text-6xl xl:text-7xl">L’attesa diventa <span className="bg-gradient-to-r from-teal-700 via-cyan-600 to-blue-700 bg-clip-text text-transparent">leggibile.</span></h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-slate-600">Questa applicazione è l’output dimostrativo di un progetto più ampio di UX e service design. Il focus è riprogettare il modo in cui il Pronto Soccorso comunica con pazienti, accompagnatori e personale.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row sm:flex-wrap"><button className="btn-primary bg-[#102f46] hover:bg-[#173f5d]" onClick={() => navigate('/project')}>Leggi il progetto UX <ArrowRight size={18} /></button><button className="btn-secondary" onClick={() => navigate('/mobile')}>Esplora la demo</button></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-3 text-sm font-semibold text-slate-600"><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-teal-600" /> Privacy by design</span><span className="flex items-center gap-2"><HeartHandshake size={17} className="text-teal-600" /> Linguaggio inclusivo</span><span className="flex items-center gap-2"><TimerReset size={17} className="text-teal-600" /> Aggiornamenti chiari</span></div></div>
      <div className="relative mx-auto w-full max-w-[490px]"><div className="absolute -inset-8 rounded-full bg-gradient-to-br from-teal-300/25 to-blue-300/25 blur-2xl" /><div className="card relative overflow-hidden rounded-[28px] border-white/70 p-3 shadow-[0_30px_80px_-35px_rgba(16,47,70,.45)]"><div className="rounded-[22px] bg-gradient-to-br from-[#102f46] via-[#164761] to-teal-800 p-6 text-white"><div className="flex items-center justify-between"><span className="text-xs font-black uppercase tracking-[.15em] text-cyan-200">Tracking ticket</span><span className="rounded-full bg-cyan-300/20 px-3 py-1 text-xs font-bold text-cyan-100 ring-1 ring-cyan-200/20">Preavviso</span></div><div className="mt-6 flex items-end justify-between"><div><p className="text-5xl font-black tracking-[.12em]">C12</p><p className="mt-2 text-sm font-semibold text-blue-100">Sta arrivando il tuo turno</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10"><BellRing size={22} /></span></div></div><div className="grid grid-cols-5 gap-2 p-5">{[['B',3,'bg-white border-slate-200 text-slate-700'],['V',7,'bg-emerald-500 text-white'],['C',5,'bg-blue-500 text-white'],['A',5,'bg-orange-500 text-white'],['R',1,'bg-red-500 text-white']].map(([code,total,tone]) => <div key={String(code)} className={`rounded-xl border py-2.5 text-center ${tone}`}><span className="block text-[9px] font-bold">{code}</span><strong className="text-xl">{total}</strong></div>)}</div><div className="mx-5 mb-5 rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between text-xs"><span className="font-bold text-slate-500">Codice Azzurro oggi</span><strong className="text-[#102f46]">Attesa 30–60 min</strong></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-slate-200"><div className="h-full w-[58%] rounded-full bg-gradient-to-r from-teal-500 to-blue-500" /></div></div></div></div></div></section>

  <section className="container-page py-16"><div className="overflow-hidden rounded-[28px] bg-gradient-to-r from-[#102f46] via-[#164761] to-[#165d68] text-white shadow-soft"><div className="grid items-center gap-8 p-7 sm:p-10 lg:grid-cols-[1fr_auto]"><div><p className="text-xs font-black uppercase tracking-[.18em] text-cyan-300">Il progetto dietro l’interfaccia</p><h2 className="mt-3 max-w-3xl text-3xl font-black tracking-tight sm:text-4xl">L’app non è il progetto. È la forma visibile di un nuovo servizio informativo.</h2><p className="mt-4 max-w-2xl text-sm leading-relaxed text-blue-100">Ricerca sul campo, pain point, emozioni, personas, benchmark e opportunità convergono in un ecosistema di touchpoint coordinati.</p></div><button onClick={() => navigate('/project')} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 py-3 font-bold text-[#102f46] shadow-lg transition hover:-translate-y-0.5">Leggi il case study <ArrowRight size={18} /></button></div></div></section>

  <section className="container-page py-10"><div className="mb-8 max-w-2xl"><p className="eyebrow">Prima la situazione, poi il tempo</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Una fotografia trasparente del momento.</h2><p className="mt-3 text-slate-600">Numeri aggregati e anonimi mostrano come sono distribuite priorità e fasi del percorso.</p></div><CurrentSituationOverview patients={patients} compact /></section>

  <section className="container-page pb-24 pt-14"><div className="max-w-2xl"><p className="eyebrow">Un servizio, tre interfacce</p><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Informazioni coerenti, dal ticket alla visita.</h2></div><div className="mt-9 grid gap-5 lg:grid-cols-3">{experiences.map(({ icon: Icon, number, title, text, path, action, tone }) => <article key={path} className="card group relative overflow-hidden p-7 transition hover:-translate-y-1 hover:shadow-soft"><div className={`absolute inset-x-0 top-0 h-24 bg-gradient-to-b ${tone} opacity-70`} /><div className="relative flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-[#102f46] shadow-sm"><Icon /></span><span className="text-4xl font-black text-slate-100">{number}</span></div><h3 className="relative mt-7 text-xl font-black">{title}</h3><p className="relative mt-2 min-h-[48px] text-sm leading-relaxed text-slate-600">{text}</p><button onClick={() => navigate(path)} className="relative mt-6 inline-flex items-center gap-2 text-sm font-bold text-teal-700">{action}<ArrowRight size={16} className="transition group-hover:translate-x-1" /></button></article>)}</div></section></>
}
