import { useState, type ReactNode } from 'react'
import type { LucideIcon } from 'lucide-react'
import { Activity, ArrowRight, BellRing, Building2, CircleAlert, Eye, HeartHandshake, Lightbulb, Map, MessageCircle, Monitor, Navigation, ShieldCheck, Smartphone, Sparkles, Stethoscope, Target, Users } from 'lucide-react'
import clsx from 'clsx'
import { navigate } from '../lib/navigation'
import { BrandMark } from '../components/BrandMark'

const tabs = ['Overview', 'Contesto', 'Ricerca', 'Interviste', 'Benchmark & tool', 'Pain point', 'Insight', 'Personas', 'Opportunità', 'Concept', 'MVP', 'Impatto atteso'] as const
type Tab = typeof tabs[number]

function SectionTitle({ eyebrow, title, children }: { eyebrow: string; title: string; children?: ReactNode }) {
  return <div className="max-w-3xl"><p className="eyebrow">{eyebrow}</p><h2 className="mt-3 text-3xl font-black tracking-tight text-ink sm:text-4xl">{title}</h2>{children && <div className="mt-4 text-base leading-relaxed text-slate-600">{children}</div>}</div>
}

function FeatureCard({ icon: Icon, title, children, index }: { icon: LucideIcon; title: string; children: ReactNode; index?: string }) {
  return <article className="card group relative h-full overflow-hidden p-5 transition hover:-translate-y-0.5 hover:shadow-soft sm:p-6"><div className="absolute inset-x-0 top-0 h-20 bg-gradient-to-b from-teal-50/70 to-transparent" /><div className="relative flex items-start justify-between gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-white text-teal-700 shadow-sm ring-1 ring-teal-100"><Icon size={21} /></span>{index && <span className="text-3xl font-black text-slate-100">{index}</span>}</div><h3 className="relative mt-5 text-lg font-bold text-ink">{title}</h3><div className="relative mt-2 text-sm leading-relaxed text-slate-600">{children}</div></article>
}

function ServiceFlowDiagram() {
  const steps = ['Arrivo', 'Triage', 'Attesa', 'Chiamata', 'Visita', 'Esami / Referto', 'Uscita']
  return <div className="mt-9 rounded-2xl border border-slate-200 bg-white p-5 shadow-card"><div className="flex items-end justify-between"><div><p className="eyebrow">Service flow</p><h3 className="mt-1 text-xl font-black">Il percorso informativo</h3></div><span className="hidden text-xs font-bold text-slate-400 sm:block">Ogni passaggio richiede orientamento</span></div><div className="mt-6 grid gap-2 sm:grid-cols-7">{steps.map((step, index) => <div key={step} className="relative flex items-center gap-2 sm:block"><span className={clsx('grid h-9 w-9 shrink-0 place-items-center rounded-full text-xs font-black', index === 0 || index === steps.length - 1 ? 'bg-[#102f46] text-white' : 'bg-teal-50 text-teal-800 ring-1 ring-teal-200')}>{index + 1}</span><p className="text-sm font-bold sm:mt-3 sm:text-xs">{step}</p>{index < steps.length - 1 && <span className="ml-auto h-px flex-1 bg-slate-200 sm:absolute sm:left-10 sm:top-[18px] sm:ml-0 sm:w-[calc(100%-2.5rem)]" />}</div>)}</div></div>
}

function AsIsToBeDiagram() {
  const asIs = ['Attesa opaca', 'Domande continue', 'Cartelli obsoleti', 'Personale sovraccarico']
  const toBe = ['Attesa leggibile', 'Aggiornamenti chiari', 'Utenti orientati', 'Personale meno interrotto']
  return <div className="mt-9 grid gap-4 lg:grid-cols-[1fr_auto_1fr]"><div className="rounded-2xl border border-red-100 bg-gradient-to-br from-red-50 to-white p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-red-700">As is</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{asIs.map((item) => <p key={item} className="rounded-xl bg-white p-3 text-sm font-bold text-slate-700 shadow-sm">{item}</p>)}</div></div><span className="grid place-items-center text-slate-300"><ArrowRight className="rotate-90 lg:rotate-0" size={28} /></span><div className="rounded-2xl border border-teal-100 bg-gradient-to-br from-teal-50 to-blue-50 p-6"><p className="text-xs font-black uppercase tracking-[.18em] text-teal-700">To be</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{toBe.map((item) => <p key={item} className="rounded-xl bg-white p-3 text-sm font-bold text-[#102f46] shadow-sm">{item}</p>)}</div></div></div>
}

function ConceptDiagram() {
  return <div className="mt-9 rounded-[26px] bg-gradient-to-br from-[#102f46] via-[#164761] to-[#155e68] p-5 text-white sm:p-8"><div className="mx-auto grid max-w-5xl gap-4 lg:grid-cols-[1fr_180px_1fr] lg:items-center"><div className="grid gap-3">{layers.slice(0, 2).map(({ title, icon: Icon }) => <div key={title} className="flex items-center gap-3 rounded-xl bg-white/10 p-4 ring-1 ring-white/10"><Icon className="text-cyan-300" /><strong>{title}</strong></div>)}</div><div className="grid h-36 place-items-center rounded-full border border-cyan-300/30 bg-white/10 text-center shadow-2xl shadow-cyan-950/20"><div><Sparkles className="mx-auto text-cyan-300" /><strong className="mt-2 block text-sm">Experience<br />Redesign</strong></div></div><div className="grid gap-3">{layers.slice(2).map(({ title, icon: Icon }) => <div key={title} className="flex items-center gap-3 rounded-xl bg-white/10 p-4 ring-1 ring-white/10"><Icon className="text-cyan-300" /><strong>{title}</strong></div>)}</div></div></div>
}

const observations = ['Monitor informativo spento o non percepito', 'Assenza di informazioni cartacee chiare', 'Cartelli scritti a mano o non coordinati', 'Cartellonistica datata e non aggiornata', 'Codici triage obsoleti, senza codice azzurro', 'Bagni e servizi non dichiarati chiaramente', 'Necessità continua di chiedere al personale', 'Sedute vecchie o rotte: scarsa cura percepita', 'Senza personale presente, l’utente non sa cosa fare']
const methods = ['Osservazione diretta', 'Service safari', 'Analisi touchpoint', 'Analisi dei flussi informativi', 'Mappatura delle evidenze', 'Definizione delle ipotesi']
const patientQuestions = ['Qual è il momento in cui ti senti più perso?', 'Quale informazione vorresti avere senza chiederla?', 'Quando hai iniziato a preoccuparti durante l’attesa?', 'Hai capito il significato del tuo codice triage?', 'Sapevi dove trovare bagno, uscita o distributori?']
const staffQuestions = ['Quali domande ricevete più spesso?', 'Quali richieste interrompono di più il lavoro?', 'Quali informazioni potrebbero essere automatizzate?', 'In quali momenti si genera più tensione con i pazienti?']
const painGroups = [
  { title: 'Utente', icon: Users, items: ['Non sa cosa fare prima del triage', 'Non capisce cosa succede dopo il triage', 'Non capisce perché altri entrano prima', 'Non vede avanzamento', 'Teme di essere stato dimenticato', 'Non trova i servizi essenziali'] },
  { title: 'Personale', icon: Stethoscope, items: ['Riceve domande ripetitive', 'Deve urlare nomi o ticket', 'Viene interrotto durante attività critiche', 'Assorbe rabbia e frustrazione', 'Lavora in un clima emotivo deteriorato'] },
  { title: 'Ambiente', icon: Building2, items: ['Cartellonistica incoerente', 'Fogli obsoleti', 'Servizi non segnalati', 'Sedute danneggiate', 'Poca manutenzione percepita'] },
]
const insights = ['L’attesa è più tollerabile quando è comprensibile.', 'Le persone non cercano solo un tempo: cercano conferma che il sistema stia funzionando.', 'L’assenza di informazione trasforma il personale nel bersaglio della frustrazione.', 'La sfiducia nasce quando l’utente non riesce a interpretare ciò che vede.', 'Un ambiente poco curato comunica implicitamente disorganizzazione.']
const personas = [
  { name: 'Mario', age: 68, role: 'Paziente', initials: 'MA', tone: 'from-blue-100 to-cyan-50 text-blue-800', quote: 'Vorrei solo sapere se si ricordano di me.', profile: 'Non è digitale, è preoccupato e teme di essere dimenticato.', need: 'Sapere se è stato preso in carico.', pain: 'Non capisce il codice triage e non sa quanto attendere.' },
  { name: 'Sara', age: 42, role: 'Accompagnatrice', initials: 'SA', tone: 'from-violet-100 to-fuchsia-50 text-violet-800', quote: 'Devo restare pronta, ma non so per cosa.', profile: 'Vuole capire cosa succede al familiare e rimanere pronta.', need: 'Ricevere aggiornamenti senza dover chiedere.', pain: 'Non sa quando avvicinarsi o aspettare.' },
  { name: 'Luca', age: 38, role: 'Infermiere di triage', initials: 'LU', tone: 'from-teal-100 to-emerald-50 text-teal-800', quote: 'Ogni domanda è lecita, ma interrompe un’attività.', profile: 'Gestisce pazienti, priorità e tensioni emotive.', need: 'Ridurre interruzioni e domande ripetitive.', pain: 'Il sistema non comunica: deve ripetere le stesse informazioni.' },
  { name: 'Anna', age: 57, role: 'Operatrice amministrativa', initials: 'AN', tone: 'from-amber-100 to-orange-50 text-amber-800', quote: 'Spesso sono il primo punto a cui chiedono tutto.', profile: 'È spesso il primo punto di contatto percepito.', need: 'Dare indicazioni semplici senza conflitti continui.', pain: 'Le informazioni mancanti generano richieste non pertinenti.' },
]
const opportunities = [
  ['Rendere visibile la situazione', 'Mostrare quanti pazienti sono presenti per codice e fase del percorso.'],
  ['Ridurre l’opacità dell’attesa', 'Passare da una semplice attesa a un percorso comprensibile.'],
  ['Proteggere il personale', 'Automatizzare le informazioni ripetitive per liberare tempo e ridurre tensione.'],
  ['Coordinare accompagnatori e dimissioni', 'Avvisare quando il paziente è in preparazione uscita o pronto.'],
  ['Migliorare fiducia ambientale', 'Segnaletica, sedute e servizi devono trasmettere cura e affidabilità.'],
]
const layers = [
  { title: 'Display pubblico', icon: Monitor, items: ['Situazione per codici', 'Chiamate', 'Preparazione uscita', 'QR'] },
  { title: 'Mobile paziente', icon: Smartphone, items: ['Ticket senza login', 'Stato personale', 'Situazione attuale', 'Notifiche demo'] },
  { title: 'Dashboard operatore', icon: Activity, items: ['Inserimento paziente', 'Aggiornamento stato', 'Chiamata', 'Dimissione'] },
  { title: 'Comunicazione fisica', icon: Map, items: ['Ticket cartaceo', 'Segnaletica', 'Istruzioni sintetiche', 'Servizi dichiarati'] },
]
const metrics = ['Riduzione domande ripetitive al personale', 'Maggiore comprensione del percorso', 'Minore percezione di abbandono', 'Migliore coordinamento accompagnatori', 'Riduzione frizione durante chiamata e dimissione', 'Maggiore fiducia nel servizio']

function OverviewTab() { const chain = ['Informazione assente', 'Confusione', 'Domande ripetitive', 'Stress sul personale', 'Clima peggiore', 'Esperienza frustrante']; return <div><SectionTitle eyebrow="Overview" title="Da sistema informativo a esperienza di servizio">Il sistema VideoSoccorso fornisce dati sull’affollamento, ma l’esperienza osservata mostra un problema più profondo: l’informazione non è sufficientemente visibile, contestuale e utile nel momento dell’attesa.</SectionTitle><div className="mt-9 grid gap-4 md:grid-cols-3"><FeatureCard icon={CircleAlert} title="Problema">Attesa opaca e scarsa comprensione del percorso</FeatureCard><FeatureCard icon={Target} title="Obiettivo">Ridurre incertezza, domande ripetitive e frizione</FeatureCard><FeatureCard icon={Sparkles} title="Output">Display pubblico, tracking ticket, dashboard operatore, pagina mobile</FeatureCard></div><div className="mt-8 rounded-2xl border border-slate-200 bg-gradient-to-br from-white to-slate-50 p-5 shadow-card"><p className="eyebrow">Diagramma del problema</p><div className="mt-5 grid gap-2 md:grid-cols-6">{chain.map((item, index) => <div key={item} className="flex items-center gap-2 md:block"><div className={clsx('rounded-xl p-3 text-sm font-bold md:min-h-20', index === 0 ? 'bg-red-50 text-red-800' : index === chain.length - 1 ? 'bg-[#102f46] text-white' : 'bg-slate-100 text-slate-700')}>{item}</div>{index < chain.length - 1 && <ArrowRight className="shrink-0 text-slate-300 md:mx-auto md:mt-2 md:rotate-90" size={18} />}</div>)}</div></div></div> }

function ContextTab() { return <div><SectionTitle eyebrow="Contesto" title="Un ambiente ad alta tensione emotiva">Il Pronto Soccorso è un contesto in cui le persone arrivano con paura, dolore, stanchezza o preoccupazione. Senza informazioni, ogni minuto viene interpretato come abbandono o ingiustizia.</SectionTitle><h3 className="mt-9 text-lg font-bold">Osservazioni sul campo</h3><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{observations.map((item, i) => <div key={item} className="card flex gap-3 p-4"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-slate-100 text-xs font-black text-slate-500">{i + 1}</span><p className="text-sm font-semibold leading-relaxed text-slate-700">{item}</p></div>)}</div><blockquote className="mt-8 rounded-2xl bg-[#102f46] p-6 text-xl font-bold leading-relaxed text-white sm:p-8 sm:text-2xl">“Lo spazio comunica prima delle parole: sedie rotte, cartelli obsoleti e informazioni assenti riducono la fiducia nel servizio.”</blockquote></div> }

function ResearchTab() { const phases = [['01', 'Osservare', 'Raccogliere segnali nello spazio, nei comportamenti e nelle richieste.'], ['02', 'Interpretare', 'Collegare touchpoint, emozioni e carico operativo.'], ['03', 'Formulare', 'Trasformare evidenze in ipotesi e domande verificabili.'], ['04', 'Validare', 'Testare interviste, prototipi e KPI nel contesto reale.']]; return <div><SectionTitle eyebrow="Ricerca" title="Metodo di ricerca">Un processo leggero ma strutturato, orientato a osservare il servizio nei punti in cui informazione, spazio e persone si incontrano.</SectionTitle><div className="mt-8 flex flex-wrap gap-2">{methods.map((method) => <span key={method} className="rounded-full border border-teal-200 bg-teal-50 px-4 py-2 text-sm font-bold text-teal-800">{method}</span>)}</div><div className="mt-9 grid gap-4 md:grid-cols-4">{phases.map(([number, title, text]) => <article key={number} className="card p-5"><span className="text-3xl font-black text-teal-100">{number}</span><h3 className="mt-4 font-bold">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600">{text}</p></article>)}</div><ServiceFlowDiagram /><div className="mt-8 rounded-2xl border border-blue-100 bg-blue-50 p-5 text-sm leading-relaxed text-blue-900"><strong>Principio:</strong> distinguere sempre ciò che è stato osservato, ciò che è un’interpretazione e ciò che deve ancora essere validato.</div></div> }

function InterviewsTab() { return <div><SectionTitle eyebrow="Interviste" title="Un protocollo per ascoltare esperienza e lavoro">Le interviste servono a verificare dove nasce il disorientamento e quali richieste informative sottraggono tempo alle attività di cura.</SectionTitle><div className="mt-8 rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-relaxed text-amber-900"><strong>Stato della ricerca.</strong> Le domande sono un protocollo da applicare sul campo, non risultati già validati.</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><FeatureCard icon={Users} title="Pazienti e accompagnatori"><ul className="space-y-3">{patientQuestions.map((q) => <li key={q} className="flex gap-2"><MessageCircle size={16} className="mt-0.5 shrink-0 text-teal-600" />“{q}”</li>)}</ul></FeatureCard><FeatureCard icon={Stethoscope} title="Personale"><ul className="space-y-3">{staffQuestions.map((q) => <li key={q} className="flex gap-2"><MessageCircle size={16} className="mt-0.5 shrink-0 text-teal-600" />“{q}”</li>)}</ul></FeatureCard></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="card p-4"><p className="text-xs font-black uppercase tracking-wider text-teal-700">Campione</p><p className="mt-2 text-sm font-semibold">Pazienti, accompagnatori, triage e amministrazione</p></div><div className="card p-4"><p className="text-xs font-black uppercase tracking-wider text-teal-700">Formato</p><p className="mt-2 text-sm font-semibold">Interviste brevi, contestuali e non invasive</p></div><div className="card p-4"><p className="text-xs font-black uppercase tracking-wider text-teal-700">Output</p><p className="mt-2 text-sm font-semibold">Pattern, citazioni, momenti critici e priorità</p></div></div></div> }

function BenchmarkTab() { const tools = [{ title: 'VideoSoccorso', icon: Monitor, lens: 'Affollamento e attese', learn: 'Il dato esiste, ma deve diventare esperienza contestuale.' }, { title: 'Display pubblici', icon: Eye, lens: 'Visibilità da lontano', learn: 'Gerarchie, contrasto e anonimato sono requisiti di servizio.' }, { title: 'Ticket tracking', icon: Smartphone, lens: 'Stato personale', learn: 'Un codice anonimo può ridurre incertezza senza login.' }, { title: 'Queue management', icon: Activity, lens: 'Flussi operativi', learn: 'Stati e chiamate devono essere semplici da aggiornare.' }, { title: 'Segnaletica fisica', icon: Map, lens: 'Orientamento ambientale', learn: 'Digitale e spazio devono comunicare la stessa cosa.' }]; return <div><SectionTitle eyebrow="Benchmark & tool" title="Studiare gli strumenti, non copiarne l’interfaccia">Il benchmark osserva cosa ogni famiglia di strumenti rende possibile e dove interrompe l’esperienza. Il valore nasce dalla loro integrazione nel servizio.</SectionTitle><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{tools.map(({ title, icon: Icon, lens, learn }) => <article key={title} className="card p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-teal-50 text-teal-700"><Icon size={20} /></span><h3 className="mt-4 font-bold">{title}</h3><p className="mt-1 text-xs font-bold uppercase tracking-wide text-slate-400">{lens}</p><p className="mt-4 text-sm leading-relaxed text-slate-600">{learn}</p></article>)}</div><div className="mt-8 rounded-2xl bg-[#102f46] p-6 text-white"><p className="eyebrow text-teal-300">Criteri di valutazione</p><div className="mt-4 grid gap-3 text-sm font-semibold sm:grid-cols-2 lg:grid-cols-4"><p>Chiarezza immediata</p><p>Accessibilità e distanza</p><p>Privacy e anonimato</p><p>Carico sul personale</p><p>Continuità tra touchpoint</p><p>Velocità di aggiornamento</p><p>Gestione delle eccezioni</p><p>Fiducia percepita</p></div></div></div> }

function PainTab() { return <div><SectionTitle eyebrow="Pain point" title="Il problema non è solo aspettare. È non capire." /><div className="mt-9 grid gap-5 lg:grid-cols-3">{painGroups.map(({ title, icon: Icon, items }) => <FeatureCard key={title} icon={Icon} title={title}><ul className="space-y-2.5">{items.map((item) => <li key={item} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-teal-500" />{item}</li>)}</ul></FeatureCard>)}</div><div className="mt-8 flex items-center gap-4 rounded-2xl border border-red-100 bg-red-50 p-6"><MessageCircle className="shrink-0 text-red-600" size={28} /><p className="text-lg font-bold text-red-900">Quando il sistema non comunica, il personale diventa l’interfaccia umana del servizio.</p></div></div> }

function InsightTab() { return <div><SectionTitle eyebrow="Insight" title="Insight principali" /><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{insights.map((item, i) => <article key={item} className="card p-5"><span className="text-4xl font-black text-teal-100">0{i + 1}</span><p className="mt-4 text-base font-bold leading-relaxed text-ink">{item}</p></article>)}</div><div className="mt-8 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><div className="card p-6"><p className="eyebrow">Emozioni osservate</p><div className="mt-4 flex flex-wrap gap-2">{['Sfiducia', 'Frustrazione', 'Rabbia', 'Confusione', 'Paura'].map((emotion) => <span key={emotion} className="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-bold text-slate-700">{emotion}</span>)}</div></div><div className="rounded-2xl bg-[#102f46] p-6 text-base leading-relaxed text-blue-50">Queste emozioni non restano individuali: diventano <strong className="text-white">clima</strong>. Un clima teso rende il personale più difensivo, meno disponibile e meno partecipativo, peggiorando ulteriormente l’esperienza.</div></div></div> }

function PersonasTab() { return <div><SectionTitle eyebrow="Personas" title="Quattro prospettive sullo stesso servizio" /><div className="mt-8 grid gap-5 md:grid-cols-2">{personas.map((persona) => <article key={persona.name} className="card overflow-hidden"><div className={`bg-gradient-to-br p-6 ${persona.tone}`}><div className="flex items-center gap-4"><span className="grid h-16 w-16 shrink-0 place-items-center rounded-full bg-white/80 text-xl font-black shadow-sm ring-4 ring-white/35">{persona.initials}</span><div><h3 className="text-xl font-black">{persona.name}, {persona.age}</h3><p className="text-sm font-bold opacity-80">{persona.role}</p></div></div><blockquote className="mt-5 text-base font-bold leading-relaxed">“{persona.quote}”</blockquote></div><div className="p-6"><p className="text-sm leading-relaxed text-slate-600">{persona.profile}</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-emerald-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-emerald-700">Bisogno</p><p className="mt-1 text-sm font-semibold">{persona.need}</p></div><div className="rounded-xl bg-red-50 p-3"><p className="text-[10px] font-bold uppercase tracking-wider text-red-700">Pain point</p><p className="mt-1 text-sm font-semibold">{persona.pain}</p></div></div></div></article>)}</div></div> }

function OpportunityTab() { return <div><SectionTitle eyebrow="Opportunità" title="Dove può intervenire il redesign" /><AsIsToBeDiagram /><div className="mt-9 grid gap-4 md:grid-cols-2">{opportunities.map(([title, text], i) => <FeatureCard key={title} icon={[Eye, Navigation, ShieldCheck, BellRing, HeartHandshake][i]} title={title} index={`0${i + 1}`}>{text}</FeatureCard>)}</div></div> }

function ConceptTab() { return <div><SectionTitle eyebrow="Concept" title="VideoSoccorso Experience Redesign">Il concept trasforma VideoSoccorso da visualizzazione dell’affollamento a ecosistema informativo di servizio.</SectionTitle><ConceptDiagram /><div className="relative mt-6 grid gap-4 lg:grid-cols-4">{layers.map(({ title, icon: Icon, items }, i) => <article key={title} className="card relative p-5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#102f46] text-white"><Icon size={21} /></span><p className="mt-5 text-xs font-black uppercase tracking-wider text-teal-700">Layer {i + 1}</p><h3 className="mt-1 text-lg font-bold">{title}</h3><ul className="mt-4 space-y-2 text-sm text-slate-600">{items.map((item) => <li key={item} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-teal-500" />{item}</li>)}</ul></article>)}</div></div> }

function MvpTab() { const demos = [{ title: 'Prova come paziente', icon: Smartphone, path: '/mobile' }, { title: 'Apri display sala', icon: Monitor, path: '/display' }, { title: 'Login operatore demo', icon: ShieldCheck, path: '/login' }]; return <div><SectionTitle eyebrow="MVP" title="L’app come prototipo dell’esperienza">Il prototipo non simula un sistema ospedaliero reale, ma rende tangibile la proposta di servizio. Il paziente non accede con dati personali: usa solo il ticket ricevuto al triage.</SectionTitle><div className="mt-8 grid gap-4 md:grid-cols-3">{demos.map(({ title, icon: Icon, path }) => <button key={path} onClick={() => navigate(path)} className="card group flex min-h-40 flex-col items-start p-5 text-left transition hover:-translate-y-1 hover:shadow-soft"><Icon className="text-teal-700" /><span className="mt-auto flex w-full items-center justify-between text-lg font-bold">{title}<ArrowRight className="transition group-hover:translate-x-1" size={19} /></span></button>)}</div><div className="mt-6 rounded-2xl bg-slate-100 p-5"><p className="text-sm font-bold">Credenziali demo</p><div className="mt-2 flex flex-wrap gap-x-8 gap-y-2 text-sm text-slate-600"><p>Email: <strong className="text-ink">demo@ospedale.it</strong></p><p>Password: <strong className="text-ink">demo123</strong></p></div></div></div> }

function ImpactTab() { return <div><SectionTitle eyebrow="Impatto atteso" title="Cosa migliora"><span className="inline-flex rounded-full bg-amber-50 px-3 py-1 text-xs font-bold text-amber-800">KPI ipotetici da validare</span></SectionTitle><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{metrics.map((metric, i) => <div key={metric} className="card flex items-start gap-4 p-5"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-teal-50 text-sm font-black text-teal-700">{i + 1}</span><p className="font-bold leading-relaxed">{metric}</p></div>)}</div><blockquote className="mt-9 rounded-2xl bg-gradient-to-r from-[#102f46] to-teal-800 p-7 text-2xl font-black leading-relaxed text-white sm:p-10 sm:text-3xl">“Il progetto non promette di accorciare l’attesa. Promette di renderla leggibile, guidata e meno ostile.”</blockquote></div> }

const panels: Record<Tab, () => ReactNode> = { Overview: OverviewTab, Contesto: ContextTab, Ricerca: ResearchTab, Interviste: InterviewsTab, 'Benchmark & tool': BenchmarkTab, 'Pain point': PainTab, Insight: InsightTab, Personas: PersonasTab, Opportunità: OpportunityTab, Concept: ConceptTab, MVP: MvpTab, 'Impatto atteso': ImpactTab }

export function ProjectPage() {
  const [activeTab, setActiveTab] = useState<Tab>('Overview')
  const Panel = panels[activeTab]
  return <><section className="relative overflow-hidden bg-[linear-gradient(135deg,#0f2d45_0%,#153f5b_48%,#155e68_100%)] text-white"><div className="absolute -right-20 -top-20 h-[460px] w-[460px] rounded-full bg-cyan-400/15 blur-3xl" /><div className="absolute -bottom-32 left-1/3 h-80 w-80 rounded-full bg-violet-400/10 blur-3xl" /><div className="container-page relative grid items-center gap-12 py-16 sm:py-24 lg:grid-cols-[1.2fr_.8fr]"><div className="max-w-4xl"><BrandMark inverse /><p className="mt-8 text-sm font-black uppercase tracking-[.2em] text-teal-300">UX · Service Design · Healthcare</p><h1 className="mt-5 text-4xl font-black leading-tight tracking-[-.04em] sm:text-6xl">Redesign dell’esperienza informativa in Pronto Soccorso</h1><p className="mt-6 max-w-3xl text-lg leading-relaxed text-blue-100">Un progetto di UX e service design per ridurre incertezza, frustrazione e carico comunicativo sul personale sanitario.</p><p className="mt-7 max-w-3xl text-base leading-relaxed text-blue-100/80">Questo progetto nasce dall’osservazione di un’esperienza critica: in Pronto Soccorso l’attesa non è solo lunga, è spesso opaca. Quando le persone non sanno cosa succede, iniziano a chiedere, interpretare, dubitare.</p></div><aside className="hidden lg:block"><div className="rounded-[26px] border border-white/15 bg-white/10 p-5 shadow-2xl shadow-blue-950/30 backdrop-blur"><p className="text-xs font-black uppercase tracking-[.16em] text-cyan-300">Il sistema di esperienza</p><div className="mt-5 grid gap-3">{[['01','Comprendere','Ricerca ed emozioni'],['02','Orientare','Touchpoint coordinati'],['03','Rendere tangibile','MVP e prototipi']].map(([number,title,text]) => <div key={number} className="flex items-center gap-4 rounded-xl bg-white/10 p-4"><span className="text-2xl font-black text-cyan-300">{number}</span><div><strong className="block">{title}</strong><span className="text-xs text-blue-100">{text}</span></div></div>)}</div></div></aside><div className="lg:col-span-2 max-w-3xl rounded-2xl border border-teal-300/25 bg-white/10 p-5 backdrop-blur"><p className="flex gap-3 text-base font-bold leading-relaxed text-white"><Lightbulb className="mt-0.5 shrink-0 text-teal-300" />L’applicazione non è il progetto: è uno degli output. Il vero progetto è il redesign dell’esperienza informativa del servizio.</p></div></div></section>
    <nav className="sticky top-[104px] z-30 border-b border-slate-200 bg-white/95 shadow-sm backdrop-blur" aria-label="Sezioni del progetto"><div className="container-page overflow-x-auto"><div className="flex min-w-max gap-1 py-2">{tabs.map((tab) => <button key={tab} onClick={() => setActiveTab(tab)} className={clsx('min-h-10 rounded-lg px-3 py-2 text-xs font-bold transition sm:text-sm', activeTab === tab ? 'bg-[#102f46] text-white' : 'text-slate-600 hover:bg-slate-100')}>{tab}</button>)}</div></div></nav>
    <main className="container-page min-h-[620px] py-12 sm:py-16"><Panel /></main></>
}
