import clsx from 'clsx'
import { useMemo } from 'react'
import { getCurrentSituation } from '../lib/currentSituation'
import type { Patient, Priority } from '../types'

const rowStyles: Record<Priority, string> = {
  red: 'bg-red-500', orange: 'bg-orange-500', blue: 'bg-blue-500', green: 'bg-emerald-500', white: 'bg-slate-300',
}

export function CurrentSituationOverview({ patients, title = true, compact = false, display = false, mobile = false, focusPriority, footerText }: { patients: Patient[]; title?: boolean; compact?: boolean; display?: boolean; mobile?: boolean; focusPriority?: Priority; footerText?: string }) {
  const situation = useMemo(() => getCurrentSituation(patients), [patients])
  if (mobile) {
    const order: Priority[] = ['white', 'green', 'blue', 'orange', 'red']
    const ordered = order.map((priority) => situation.find((row) => row.priority === priority)!)
    const focused = situation.find((row) => row.priority === focusPriority) || situation[0]
    const short: Record<Priority, string> = { white: 'B', green: 'V', blue: 'C', orange: 'A', red: 'R' }
    const total = situation.reduce((sum, row) => sum + row.totalActive, 0)
    return <section className="card overflow-hidden" aria-label="Panoramica situazione attuale"><div className="flex items-end justify-between border-b px-4 py-3"><div><p className="eyebrow text-[11px]">Situazione attuale</p><h2 className="mt-0.5 text-base font-bold">Pazienti presenti ora</h2></div><span className="text-xs font-bold text-slate-500">Tot <strong className="text-lg text-ink">{total}</strong></span></div><div className="grid grid-cols-5 gap-1.5 px-4 py-3">{ordered.map((row) => <div key={row.priority} className={clsx('rounded-lg px-1 py-2 text-center text-white', row.priority === 'white' ? 'border border-slate-300 bg-white text-slate-800' : rowStyles[row.priority])}><span className="block text-[10px] font-bold">{short[row.priority]}</span><strong className="text-lg leading-none">{row.totalActive}</strong></div>)}</div><div className="border-t bg-slate-50/80 px-4 py-3"><div className="flex items-center justify-between"><p className="inline-flex items-center gap-2 text-sm font-bold"><span className={clsx('h-3 w-3 rounded-full', rowStyles[focused.priority])} />Codice {focused.label} oggi</p><span className="text-xs text-slate-500">Attesa <strong className="text-ink">{focused.indicativeWait}</strong></span></div><div className="mt-2 grid grid-cols-6 gap-1 text-center">{[['Attesa', focused.waiting], ['Pross.', focused.next], ['Chiam.', focused.called], ['Visita', focused.visiting], ['Esami', focused.examsReports], ['Uscita', focused.exitPreparing + focused.readyForDischarge]].map(([label, value]) => <div key={String(label)}><strong className="block text-base">{value}</strong><span className="text-[8px] font-medium text-slate-500">{label}</span></div>)}</div><p className="mt-2 border-t pt-2 text-[10px] text-slate-500">Dato orientativo, può variare per priorità cliniche.</p></div></section>
  }
  return <section className={clsx('card overflow-hidden', compact && 'shadow-none')} aria-label="Panoramica situazione attuale">
    {title && <div className="border-b px-5 py-4 sm:px-6"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="eyebrow">Situazione attuale</p><h2 className="mt-1 text-xl font-bold">Presenze e fasi del percorso</h2></div><p className="max-w-md text-xs leading-relaxed text-slate-500">La situazione reale viene prima della stima: le priorità cliniche possono modificare tempi e ordine di accesso.</p></div></div>}
    <div className="overflow-x-auto"><table className="w-full min-w-[920px] border-separate border-spacing-0 text-center"><thead className={clsx('bg-slate-50 font-bold uppercase tracking-wider text-slate-500', display ? 'text-xs' : 'text-[10px]')}><tr><th className="sticky left-0 z-10 bg-slate-50 px-4 py-3 text-left">Codice triage</th><th className="px-3 py-3">Totale</th><th className="px-3 py-3">In attesa</th><th className="px-3 py-3">Prossimi</th><th className="px-3 py-3">Chiamati</th><th className="px-3 py-3">In visita</th><th className="px-3 py-3">Esami/referto</th><th className="px-3 py-3">Uscita</th><th className="border-l bg-slate-100/80 px-4 py-3 font-medium text-slate-400">Attesa indicativa</th></tr></thead>
      <tbody>{situation.map((row) => <tr key={row.priority} className="group hover:bg-teal-50/30"><th className={clsx('sticky left-0 z-10 border-t bg-white px-4 text-left group-hover:bg-[#f5fbfa]', display ? 'py-2' : 'py-3')}><span className={clsx('inline-flex items-center gap-2 font-bold', display ? 'text-lg' : 'text-sm')}><span className={clsx('rounded-full ring-2 ring-white shadow-sm', display ? 'h-4 w-4' : 'h-3 w-3', rowStyles[row.priority])} />{row.label}</span></th><td className={clsx('border-t px-3', display ? 'py-2' : 'py-3')}><strong className={clsx('text-ink', display ? 'text-3xl' : 'text-xl')}>{row.totalActive}</strong><span className={clsx('mt-0.5 block uppercase tracking-wide text-slate-400', display ? 'text-[11px]' : 'text-[9px]')}>attivi</span></td>{[row.waiting, row.next, row.called, row.visiting, row.examsReports].map((value, index) => <td key={index} className={clsx('border-t px-3 font-bold', display ? 'py-2 text-2xl' : 'py-3 text-lg')}>{value}</td>)}<td className={clsx('border-t px-3', display ? 'py-2' : 'py-3')}><span className={clsx('font-bold', display ? 'text-2xl' : 'text-lg')}>{row.exitPreparing + row.readyForDischarge}</span><span className={clsx('mt-0.5 block text-slate-400', display ? 'text-[11px]' : 'text-[9px]')}>{row.readyForDischarge} pronti</span></td><td className={clsx('border-l border-t bg-slate-50/70 px-4 font-medium text-slate-500', display ? 'py-2 text-sm' : 'py-3 text-xs')}>{row.indicativeWait}</td></tr>)}</tbody>
    </table></div><div className={clsx('border-t bg-slate-50/70 px-5 py-3 leading-relaxed text-slate-500', display ? 'text-sm' : 'text-[11px]')}><strong>Nota:</strong> {footerText || 'i tempi sono indicativi. L’accesso dipende sempre dalla rivalutazione clinica e dalla priorità.'}</div>
  </section>
}
