import { useState } from 'react'
import { ArrowLeft, CheckCircle2, Ticket } from 'lucide-react'
import { useDemoData } from '../context/DemoDataContext'
import { priorityLabels } from '../lib/demoData'
import { navigate } from '../lib/navigation'
import type { Priority } from '../types'

export function PatientForm() {
  const { addPatient } = useDemoData()
  const [created, setCreated] = useState<string | null>(null)
  const [form, setForm] = useState({ firstName: '', lastName: '', age: '', reason: '', notes: '', priority: 'green' as Priority })
  const submit = (e: React.FormEvent) => { e.preventDefault(); const patient = addPatient({ ...form, age: Number(form.age) }); setCreated(patient.ticketCode) }
  if (created) return <div className="card mx-auto max-w-xl p-8 text-center"><span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2 size={34} /></span><p className="eyebrow mt-6">Ticket creato</p><h2 className="mt-2 text-4xl font-bold tracking-wider">{created}</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-relaxed text-slate-500">Il paziente può ora seguire lo stato del percorso inserendo questo codice nell’area mobile.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><button className="btn-secondary" onClick={() => navigate(`/mobile/${created}`)}>Anteprima paziente</button><button className="btn-primary" onClick={() => navigate('/operator')}>Torna alla dashboard</button></div></div>
  return <form onSubmit={submit} className="card mx-auto max-w-3xl p-6 sm:p-8"><div className="mb-7 flex items-center gap-4"><span className="grid h-12 w-12 place-items-center rounded-xl bg-teal-50 text-teal-700"><Ticket /></span><div><h2 className="text-xl font-bold">Dati del nuovo accesso</h2><p className="mt-1 text-sm text-slate-500">Inserisci solo informazioni fittizie per questa demo.</p></div></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="label" htmlFor="firstName">Nome</label><input required id="firstName" className="field" placeholder="es. Marco" value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} /></div><div><label className="label" htmlFor="lastName">Cognome</label><input required id="lastName" className="field" placeholder="es. Rinaldi" value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} /></div><div><label className="label" htmlFor="age">Età</label><input required id="age" min="0" max="120" type="number" className="field" placeholder="es. 42" value={form.age} onChange={(e) => setForm({ ...form, age: e.target.value })} /></div><div><label className="label" htmlFor="priority">Codice triage</label><select id="priority" className="field" value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value as Priority })}>{(Object.keys(priorityLabels) as Priority[]).map((priority) => <option key={priority} value={priority}>{priorityLabels[priority]}</option>)}</select></div><div className="sm:col-span-2"><label className="label" htmlFor="reason">Motivo dell’accesso</label><input required id="reason" className="field" placeholder="Descrizione sintetica" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /></div><div className="sm:col-span-2"><label className="label" htmlFor="notes">Note operatore</label><textarea id="notes" className="field min-h-24 resize-y" placeholder="Informazioni utili visibili solo agli operatori" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></div></div><div className="mt-8 flex flex-col-reverse gap-3 border-t pt-6 sm:flex-row sm:justify-end"><button type="button" className="btn-secondary" onClick={() => navigate('/operator')}><ArrowLeft size={18} /> Annulla</button><button className="btn-primary"><Ticket size={18} /> Genera ticket</button></div></form>
}
